### ISSUE TITLE
Port over changes from NCME to develop

### ISSUE THREAD

**Issue by bxie** [codeandcognition/koconut#237]
Some changes we made on the ncme2019 branch we want to keep for the primary version of koconut. @kwokwilliam and I went through all cards with `ncme2019` tag and identified all of these changes. We need to (somewhat manually) make these changes on the `develop` branch.

- [x] add line numbers to code (from #218)
- [x] fix reset button on writecode (from #227)
- [x] improve notepad UI (from #204)
- [x] Ace editor text can become not visible after writing beyond max width (#236)
- [x] fix scrolling to top of page on new exercise (from #193)

~~ fix spacing on multiple choice problems (from #228) ~~ NCME version of exercise view does not support multiple exercises so we'll keep the

Features list was compiled on [GSheet](https://docs.google.com/spreadsheets/d/1Wu195UT9GAXg9fQu8th-iqNiV6ylR0-EVvSNsjtlNus/edit#gid=0)
